<h1>30 March 2002</h1>

<table class="news">
  <tr>
    <td>
      <p>Going away for a few days.</p>
      <p>Kawaks and Nebula supplements will be started on when I
      return.</p>
    </td>
  </tr>
</table>

<h1>29 March 2002</h1>

<table class="news">
  <tr>
    <td>
      <p>The busy week of releases continues!</p>
      <p>For every CPS2Shock action there is an equal, not
      opposite <a href="Dats/Dats.php">reaction</a>. :)</p>
      <p>Released a data files (including MAME supplements) for <a href="Dats/Dats.php">Final
      Burn Alpha</a>.</p>
      <p>Released <a href="Tools/DatUtil/DatUtil.php">DatUtil
      v1.16</a>:</p>
      <p>- Added Nebula driver
      support (useful for data file validation).<br />
      - Supports the new '0x' syntax of CMPro logs.<br />
      - ZIP scanner now removes '.Zip' from filenames (case sensitive).<br />
      - Increased maximum line length to 16384 bytes (for MAME history).<br />
      - Increased maximum number of ROMs to 75000.<br />
      - Exceeding the game or ROM limits now results in a graceful exit.<br />
      - Compiled with zlib v1.1.4</p>
    </td>
  </tr>
</table>

<h1>28 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Minor improvement to the  <a href="Dats/Dats.php">Nebula</a>
      data files so that they match the drivers exactly (used a new
      DatUtil feature).<br />
      There is now no doubt that the data file generated by Nebula contains many
      errors so use mine instead!
    </td>
  </tr>
</table>

<h1>27 March 2002</h1>

<table class="news">
  <tr>
    <td>
      <p> Released data files for Mimic
      v2.00.</p>
    </td>
  </tr>
</table>

<h1>26 March 2002</h1>

<table class="news">
  <tr>
    <td>
      <p> My counter passed the 500,000 mark last night. :)</p>
      <p> I would have passed it a long time ago if there hadn't
      been long periods with it out of commission though, lol.</p>
    </td>
  </tr>
</table>

<h1>25 March 2002</h1>

<table class="news">
  <tr>
    <td>
      <p> Xray1 updated the <a href="Dats/Dats.php">MAME
      Flyers</a>  
      data file for Flyer Pack 18.</p>
      <p>Updated even more data files to match MAME v0.59 and
      Zinc v0.5:</p>
      <p><a href="Dats/Dats.php">Sony ZN-1/ZN-2</a>, <a href="Dats/Dats.php">NeoJukeBox</a>,
      <a href="Dats/Dats.php">Nebula Jukebox</a>, <a href="Dats/Dats.php">QPlayer</a></p>
    </td>
  </tr>
</table>

<h1>24 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Updated the <a href="Dats/Dats.php">CPS-1</a> data
      files (added Dynasty Wars [World]) and the <a href="Dats/Dats.php">Neo-Geo</a>
      data files to match MAME v0.59.
      <p>Released <a href="Tools/ROMBuild/ROMBuild.php">ROMBuild
      v1.12</a>:<p>Changed internals for Space Invaders Galactica
      to match MAME v0.59.<br />
      Added support for Tower of Druaga ROMs (HiVE v1.04).<p>Updated a <a href="Dats/Dats.php">JAS, JAS-Dig Dug 2 and Retrocade</a> 
      data files according to
      MAME v0.59
      <p>Uploaded Zinc
      data files.
      <p>Not another problem this weekend! My
      upload tool uploaded the wrong Zinc data file for CMPro (RomCenter was
      okay). Please re-download.
      <p> John IV has updated his CMPro and
      RomCenter data files for <a href="Dats/Dats.php">Snaps</a>,
      <a href="Dats/Dats.php">Icons</a> and <a href="Dats/Dats.php">Cabinets</a>. 
    </td>
  </tr>
</table>

<h1>23 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p><b>Important! If you downloaded your data
      files today before seeing this message then you MUST re-download them.</b>
      <p>Uploaded <a href="Dats/Dats.php">MAME</a>
      and <a href="Dats/Dats.php">MAME Changes</a> data files for
      MAME v0.59<p>Updated the <a href="Dats/Dats.php">Nebula</a>
      and <a href="Dats/Dats.php">RAINE</a>
      supplementary data files for MAME v0.59
      <p>Updated a <a href="Dats/Dats.php">VAntAGE
      and GalEmu</a> data files according to
      MAME v0.59:</p>
      <p>Released <a href="Tools/ROMBuild/ROMBuild.php">ROMBuild
      v1.11</a>:</p>
      <p>
      Changed source to compile without modification on FreeBSD.<br />
      Changed internal Neo-Geo ROM names to match MAME v0.59.<br />
      Added support for Pisces graphics ROMs (changed in MAME v0.59):
      <p><i>Xcade v0.85, MacMoon v0.86, Arcade Emulator v0.7,
      GalEmu v40.9,<br />
      PASMulator v0.22, Replay v0.04, Rockulator++ v0.98a, SAGE v1.16,<br />
      Sparcade v2.33b, VAntAGE v1.11</i>
    </td>
  </tr>
</table>

<h1>20 March 2002</h1>

<table class="news">
  <tr>
    <td>
      <p>With so many recent CPS-2 dumps it seems worth releasing
      a new <a href="Dats/Dats.php">CPS-2</a> data file.</p>
      <p>This contains all new dumps and renames so come the next
      CPS2Shock release it should only be simple XOR additions.</p>
      <p>You might also like to visit my CPS-2
      page to figure out what may be in the next release (see section towards
      the bottom).</p>
    </td>
  </tr>
</table>

<h1>17 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Released <a href="Tools/MAMEDiff/MAMEDiff.php">MAMEDiff
      v1.10</a> (minor fix release - see release notes).</p>
      <p>Updated <a href="Dats/Dats.php">Nebula</a>
      data files for the latest release (v2.1).</p>
    </td>
  </tr>
</table>

<h1>15 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Released <a href="Tools/MAMEDiff/MAMEDiff.php">MAMEDiff
      v1.09</a>&nbsp;</p>
      <p>Added the -t and -T options (brief description below).<br />
      Made CRCs case insensitive.<br />
      Minor fix to -v output.</p>
      <p><u>Explanation of the -t and -T options</u></p>
      <p>In addition to the -M, -S and -N options that produce
      CMPro dats of changed ZIPs, you can produce 'tiny' versions of the dats.
      This allows you to create a small supplementary dat for the new emulator
      that when added to the original set is 100% suitable for the new emulator
      (i.e. for emulators that support multiple ROM paths).</p>
      <p>Not only can these options be used when upgrading from
      one version of an emu to another but they can even be used when trying to
      use ROMs of one emulator with another (e.g. trying to use MAME ROMs with
      RAINE, Kawaks or Nebula). When used in this way you can use a standard
      MAME ROM set and a small emulator specific 'supplementary' ROM set for the
      emulator of your choice.
      <p>***
      <p>To correspond with this release, I am
      re-issuing the <a href="Dats/Dats.php">Nebula</a>, <a href="Dats/Dats.php">RAINE</a>
      and <a href="Dats/Dats.php">WinKawaks</a> data files to include
      'MAME Supplementary' data files.
    </td>
  </tr>
</table>

<h1>14 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Created SledgeHammer
      v0.02 data files.</p>
      <p>Not quite sure why I created them as the
      emulator doesn't actually do much yet!</p>
      <p>Has anyone worked out who the author is?
      It's not at all difficult to tell... ;)</p>
    </td>
  </tr>
</table>

<h1>4 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Updated <a href="Dats/Dats.php">Nebula
      Jukebox</a>
      data files for the latest release (v2.0a).</p>
    </td>
  </tr>
</table>

<h1>3 March 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>|Updated <a href="Dats/Dats.php">Nebula</a>
      data files for the latest release (v2.0).</p>
      <p>...and again for v2.0a.</p>
      <p>As always, the data file I provide
      corrects functionality errors that exist in the Nebula generated one.</p>
    </td>
  </tr>
</table>

<h1>26 February 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>New data files: <a href="Dats/Dats.php">RAINE
      v0.35</a> and ACE (thanks to CyrussD). </p>
    </td>
  </tr>
</table>

<h1>10 February 2002</h1>

<table class="news">
  <tr>
    <td>
      <p> Updated  <a href="Dats/Dats.php">MAME
      Flyers</a>  
      data file for Flyer Pack 17.</p>
      <p>Nine months since the last release comes <a href="Tools/MAMEDiff/MAMEDiff.php">MAMEDiff
      v1.08</a>.<br />
      The changes in this version are definitely worth having so download it
      right now!!!<br />
      I'd forgot how complex it's algorithms are... :)</p>
      <p>I also made <a href="Tools/DatUtil/DatUtil.php">DatUtil
      v1.15</a> back when Calice added Neo-Geo sound.<br />
      Not really a ground breaking release but you may as well have it.</p>
    </td>
  </tr>
</table>

<h1>7 February 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Rob updated the <a href="Dats/Dats.php">MAME Samples</a> and <a href="Dats/Dats.php">MAME
      Artwork</a>   data files (added game titles).</p>
    </td>
  </tr>
</table>

<h1>6 February 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Uploaded <a href="Dats/Dats.php">MAME</a>
      and <a href="Dats/Dats.php">MAME Changes</a> data files (for
      v0.58),</p>
      <p> <a href="Dats/Dats.php">Neo-Geo</a>,
      <a href="Dats/Dats.php">MAME Samples</a> and <a href="Dats/Dats.php">MAME
      Artwork</a>   dats.</p>
      <p>Yet more updates... <a href="Dats/Dats.php">NeoJukeBox</a>
      and <a href="Dats/Dats.php">Nebula
      Jukebox</a></p>
      <p> John IV has updated his CMPro and
      RomCenter data files for <a href="Dats/Dats.php">Snaps</a>,
      <a href="Dats/Dats.php">Icons</a> and <a href="Dats/Dats.php">Cabinets</a>. </p>
    </td>
  </tr>
</table>

<h1>4 February 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Created YAAME
      data files.</p>
    </td>
  </tr>
</table>

<h1>25 January 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Updated <a href="Dats/Dats.php">Nebula</a>
      data files for the latest release (v1.97).</p>
    </td>
  </tr>
</table>

<h1>23 January 2002</h1>

<table class="news">
  <tr>
    <td>
      <p> Updated <a href="Dats/Dats.php">CPS-2</a>, ACE
      and <a href="Dats/Dats.php">MAME
      Flyers</a>  data files.</p>
    </td>
  </tr>
</table>

<h1>7 January 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Roman made a minor fix to the <a href="Dats/Dats.php">MAME
      Flyers</a> data files.</p>
    </td>
  </tr>
</table>

<h1>5 January 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Updated
      Calice data files for v0.5.2.</p>
    </td>
  </tr>
</table>

<h1>3 January 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Good news today... John IV is now issuing CMPro and
      RomCenter data files for his <a href="Dats/Dats.php">Snaps</a>,
      <a href="Dats/Dats.php">Icons</a> and <a href="Dats/Dats.php">Cabinets</a>.</p>
      <p>I've also updated my Neo-Geo page to
      include some colour coding.<br />
      Remember that it is always kept up to date with the latest CPS-2 data
      files if you ever need to look.</td>
  </tr>
</table>

<h1>2 January 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>Updated a few data files according to
      MAME v0.57:</p>
      <p><a href="Dats/Dats.php">Neo-Geo</a>,
      <a href="Dats/Dats.php">NeoJukeBox</a>, <a href="Dats/Dats.php">Nebula
      Jukebox</a></p>
      <p>
      Calice, <a href="Dats/Dats.php">NeoRAGEx</a></p>
    </td>
  </tr>
</table>

<h1>1 January 2002</h1>
<table class="news">
  <tr>
    <td>
      <p>* * * H A P P Y&nbsp;&nbsp; N E
      W&nbsp;&nbsp; Y E A R * * *</p>
      <p>Uploaded data files for <a href="Dats/Dats.php">M1</a>
      v0.6, the emulator that sings DAY-TON-AAA...</p>
      <p>New MAME has been released (about 20
      minutes ago).</p>
      <p>Uploaded <a href="Dats/Dats.php">MAME</a>
      and <a href="Dats/Dats.php">MAME Changes</a> data files.</p>
    </td>
  </tr>
</table>
