version: '3'
services:
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    image: ${COMPOSE_PROJECT_NAME:-logiqx}_nginx:${PROJECT_NGINX_VERSION:-latest}-nginx-${NGINX_VERSION:-latest}
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ${WWW_ROOT}:/www
  php:
    build:
      context: ./php
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME:-logiqx}_php:${PROJECT_PHP_VERSION:-latest}-php-${PHP_VERSION:-latest}-fpm
    volumes:
      - ${WWW_ROOT}:/www
