
	
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <script language="php">
					// Standard PHP includes (database connection and constants)

					include ('../../Resources/Include.php');

				</script>
    <title>RAINE v0.50.15</title>
    <script language="php">
					// Include standard &lt;head> metadata

					include('../../Resources/Head.php');
				</script>
  </head>
  <body>
    <script language="php">
					// The main page content is a 3 column table (left column is the menu, right one is the news)

					echo '' . LF . LF;

					include('../../Resources/Top.php');
				</script>
    <p>
      <img src="../../Resources/Logiqx.png" width="327" height="68" alt="../../Resources/Logiqx.png"/>
    </p>
	<p>
      <img src="RAINE.png" width="82" height="40" alt="RAINE.png"/>
    </p>
	<p>578 games for RAINE v0.50.15<br/>(suitable for v0.50.17)</p>
	
	
	
	
	
	
	
		<p>These dats were generated by RAINE and cleaned up with DatUtil.</p>
	
	<table>
      <colgroup span="1" width="50%"/>
      <colgroup span="1" width="50%"/>
      <tr>
		<td>
          <p>Download <a href="RAINE%20v0.50.15%20(xml).zip">RAINE dat for CMPro + RC3</a> (222KB)</p>
          <p>
            <a href="RAINE%20v0.50.15%20(xml).zip">
              <img src="../../Resources/Disk.png" width="38" height="38" alt="Download"/>
            </a>
          </p>
        </td>
		<td>
          <p>Download <a href="RAINE%20v0.50.15%20(rc).zip">RAINE dat for ROMCenter 2</a> (83KB)</p>
          <p>
            <a href="RAINE%20v0.50.15%20(rc).zip">
              <img src="../../Resources/Disk.png" width="38" height="38" alt="Download"/>
            </a>
          </p>
        </td>
	</tr>
    </table>
	<hr/>
    <p>
      <img src="../../Resources/History.png" width="85" height="40" alt="History"/>
    </p>
    <p>
      <b>23 August 2008</b> - 
			
			Updated to match RAINE v0.50.15.
		</p>
    <p>
      <b>15 July 2008</b> - 
			
			Renamed a couple of ROMs in tnzsb - to work around a bug in RAINE v0.50.14.
		</p>
    <p>
      <b>30 June 2008</b> - 
			
			Updated to match RAINE v0.50.14.
		</p>
    <p>
      <b>4 June 2008</b> - 
			
			Updated to match RAINE v0.50.13.
		</p>
    <p>
      <b>20 April 2008</b> - 
			
			Now using Generic XML for CMPro + RC3.
		</p>
    <p>
      <b>10 March 2008</b> - 
			
			Just updated the header information and emulator version (v0.50.8).
		</p>
    <p>
      <b>8 July 2007</b> - 
			
			Updated to match RAINE v0.50.5.
		</p>
    <p>
      <b>11 June 2007</b> - 
			
			Added SHA-1 information for dkongex.
		</p>
    <p>
      <b>2 May 2007</b> - 
			
			Updated to match RAINE v0.50.4.
		</p>
    <p>
      <b>8 April 2007</b> - 
			
			Updated to match RAINE v0.50.3.
		</p>
    <p>
      <b>29 January 2007</b> - 
			
			Updated to match RAINE v0.50.2.
		</p>
    <p>
      <b>5 January 2007</b> - 
			
			Removed MAME supplements.
		</p>
    <p>
      <b>11 December 2006</b> - 
			
			Updated supplements for MAME v0.111.
		</p>
    <p>
      <b>19 November 2006</b> - 
			
			Updated supplements for MAME v0.110.
		</p>
    <p>
      <b>27 September 2006</b> - 
			
			Updated supplements for MAME v0.109.
		</p>
    <p>
      <b>28 August 2006</b> - 
			
			Updated to match RAINE v0.43.4.
		</p>
    <p>
      <b>21 August 2006</b> - 
			
			No change required for MAME v0.108.
		</p>
    <p>
      <b>24 July 2006</b> - 
			
			No change required for MAME v0.107.
		</p>
    <p>
      <b>14 May 2006</b> - 
			
			No change required for MAME v0.106.
		</p>
    <p>
      <b>5 April 2006</b> - 
			
			Updated supplements for MAME v0.105.
		</p>
    <p>
      <b>6 February 2006</b> - 
			
			Updated supplements for MAME v0.104.
		</p>
    <p>
      <b>4 January 2006</b> - 
			
			Updated supplements for MAME v0.103.
		</p>
    <p>
      <b>24 November 2005</b> - 
			
			Updated supplements for MAME v0.102.
		</p>
    <p>
      <b>10 October 2005</b> - 
			
			No change required for MAME v0.101.
		</p>
    <p>
      <b>25 September 2005</b> - 
			
			Updated to match RAINE v0.43.2.
		</p>
    <p>
      <b>17 September 2005</b> - 
			
			Updated to match RAINE v0.43.1 and MAME v0.100.
		</p>
    <p>
      <b>31 August 2005</b> - 
			
			Updated to match RAINE v0.43.0.
		</p>
    <p>
      <b>7 August 2005</b> - 
			
			Updated supplements for MAME v0.99.
		</p>
    <p>
      <b>15 July 2005</b> - 
			
			Updated supplements for MAME v0.98.
		</p>
    <p>
      <b>6 June 2005</b> - 
			
			No change required for MAME v0.97.
		</p>
    <p>
      <b>7 May 2005</b> - 
			
			Updated supplements for MAME v0.96.
		</p>
    <p>
      <b>28 March 2005</b> - 
			
			Updated to match RAINE v0.42.4. Supplements suitable for MAME v0.95.
		</p>
    <p>
      <b>6 March 2005</b> - 
			
			No change required for MAME v0.94.
		</p>
    <p>
      <b>27 February 2005</b> - 
			
			No change required for MAME v0.93.
		</p>
    <p>
      <b>13 February 2005</b> - 
			
			No change required for MAME v0.92.
		</p>
    <p>
      <b>30 January 2005</b> - 
			
			No change required for MAME v0.91.
		</p>
    <p>
      <b>4 January 2005</b> - 
			
			Updated supplements for MAME v0.90.
		</p>
    <p>
      <b>30 December 2004</b> - 
			
			Updated to match RAINE v0.42.3.
		</p>
    <p>
      <b>24 November 2004</b> - 
			
			No change required for MAME v0.89.
		</p>
    <p>
      <b>23 November 2004</b> - 
			
			Updated to match RAINE v0.42.0 (CPS-2 games added).
		</p>
    <p>
      <b>25 October 2004</b> - 
			
			No change required for MAME v0.88.
		</p>
    <p>
      <b>23 September 2004</b> - 
			
			Updated supplements for MAME v0.87.
		</p>
    <p>
      <b>10 September 2004</b> - 
			
			Updated to match RAINE v0.41.1.
		</p>
    <p>
      <b>24 August 2004</b> - 
			
			Updated supplements for MAME v0.86.
		</p>
    <p>
      <b>16 August 2004</b> - 
			
			Updated to match RAINE v0.40.5. Supplements are for MAME v0.85.
		</p>
    <p>
      <b>11 July 2004</b> - 
			
			Added SHA1 information.
		</p>
    <p>
      <b>2 July 2004</b> - 
			
			Updated supplements for MAME v0.84.<br/>Also renamed to to v0.40.4
		</p>
    <p>
      <b>5 June 2004</b> - 
			
			Updated to match RAINE v0.40.2 (11 game additions).
		</p>
    <p>
      <b>9 May 2004</b> - 
			
			No change required for MAME v0.82.
		</p>
    <p>
      <b>10 April 2004</b> - 
			
			Updated to match RAINE v0.40.0 (15 game additions).
		</p>
    <p>
      <b>7 March 2004</b> - 
			
			Updated supplementary dats for MAME v0.80.
		</p>
    <p>
      <b>2 March 2004</b> - 
			
			Updated to match RAINE v0.39.4d (1 game addition).
		</p>
    <p>
      <b>5 February 2004</b> - 
			
			Updated to match RAINE v0.39.3 (2 game additions).
		</p>
    <p>
      <b>31 January 2004</b> - 
			
			Updated supplementary dats for MAME v0.79.
		</p>
    <p>
      <b>24 January 2004</b> - 
			
			Updated to match RAINE v0.39.2 (some ROM changes and about 20 game additions).
		</p>
    <p>
      <b>13 November 2003</b> - 
			
			No change required for MAME v0.77.
		</p>
    <p>
      <b>19 October 2003</b> - 
			
			No change required for MAME v0.76.
		</p>
    <p>
      <b>14 October 2003</b> - 
			
			Updated supplementary dats for MAME v0.75.
		</p>
    <p>
      <b>18 September 2003</b> - 
			
			No change required for MAME v0.74.
		</p>
    <p>
      <b>25 August 2003</b> - 
			
			Updated to match RAINE v0.38.1 (some ROM changes and game additions).
		</p>
    <p>
      <b>5 July 2003</b> - 
			
			No update required, supplements are fine for MAME v0.71.
		</p>
    <p>
      <b>15 June 2003</b> - 
			
			No update required, supplements are fine for MAME v0.70.
		</p>
    <p>
      <b>21 May 2003</b> - 
			
			Updated supplementary dats for MAME v0.68.
		</p>
    <p>
      <b>9 April 2003</b> - 
			
			No update required, supplements are fine for MAME v0.67.
		</p>
    <p>
      <b>10 March 2003</b> - 
			
			Updated supplementary dats for MAME v0.66.
		</p>
    <p>
      <b>19 February 2003</b> - 
			
			Updated supplementary dats for MAME v0.65.
		</p>
    <p>
      <b>2 February 2003</b> - 
			
			Updated to match RAINE v0.37.3 (one game rename).
		</p>
    <p>
      <b>30 January 2003</b> - 
			
			Updated to match RAINE v0.37.2 (18 games added).<br/>Updated supplementary dats for MAME v0.64.
		</p>
    <p>
      <b>18 January 2003</b> - 
			
			Updated supplementary dats for MAME v0.63.
		</p>
    <p>
      <b>21 December 2002</b> - 
			
			Updated to match RAINE v0.37.0.<br/>Added bgaregh, hyperpac, hyperpcb, macrossp, ssmissin and tdragon2.
		</p>
    <p>
      <b>30 November 2002</b> - 
			
			Updated to match RAINE v0.36.2.
		</p>
    <p>
      <b>1 October 2002</b> - 
			
			Updated to match RAINE v0.36.1 (5 games added).
		</p>
    <p>
      <b>2 June 2002</b> - 
			
			Updated for RAINE v0.35b.
		</p>
    <p>
      <b>3 May 2002</b> - 
			
			Updated supplementary dats for MAME v0.60.
		</p>
    <p>
      <b>23 March 2002</b> - 
			
			Updated supplementary dats for MAME v0.59.
		</p>
    <p>
      <b>15 March 2002</b> - 
			
			Added MAME Supplementary dats.
		</p>
    <p>
      <b>26 February 2002</b> - 
			
			Updated for RAINE v0.35.
		</p>
    <p>
      <b>18 November 2001</b> - 
			
			Added acrobatm, agallet, blkheart, blkhearj, macross2 for RAINE v0.34b.
		</p>
    <p>
      <b>21 October 2001</b> - 
			
			Corrected sailormo program CRC (it is incorrectly defined in RAINE).
		</p>
    <p>
      <b>10 October 2001</b> - 
			
			Released v0.34 dats for RomCenter and CMPro.
		</p>
    <p>
      <b>7 September 2001</b> - 
			
			Released v0.33 dats for RomCenter and CMPro.
		</p>
    <p>
      <b>13 July 2001</b> - 
			
			Released v0.32a dats for RomCenter and CMPro.
		</p>
    <p>
      <b>23 June 2001</b> - 
			
			Released v0.32 dats for RomCenter and CMPro.
		</p>
    <p>
      <b>12 April 2001</b> - 
			
			Released v0.31 dats for RomCenter and CMPro.
		</p>
    <p>
      <b>11 February 2001</b> - 
			
			Released v0.30a dats for RomCenter and CMPro.
		</p>
    <p>
      <b>1 February 2001</b> - 
			
			Released v0.30 dats for RomCenter and CMPro.
		</p>
    <p>
      <b>20 August 2000</b> - 
			
			Added 20000819 dat for RomCenter.
		</p>
    <p>
      <b>15 August 2000</b> - 
			
			Added 20000809 dat for RomCenter.
		</p>
    <p>
      <b>25 July 2000</b> - 
			
			Added 20000725 dat for RomCenter.
		</p>
    <p>
      <b>6 June 2000</b> - 
			
			Added v0.28h dat for RomCenter.
		</p>
    <p>
      <b>23 May 2000</b> - 
			
			Added v0.28f and v0.28g dats for RomCenter.
		</p>
<script language="php">
					// Standard page footer (counter)

					include('../../Resources/Bottom.php');
				</script>
  </body>
</html>


